# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e9fe02edbfdae887e73b53e3df99091fde60e9b9f9f5194fd74f1bb569c44c5bc222c7fe63c5a6b22fd099087a20eb48468c53a25f51818f993efbe87ea4668

test:
  secret_key_base: daafc5e3096c63a82712033c65eb58c9d518d8f7f050501c0019bd2ea70f0283f091fb083f473d8152d916e8125eec7fb46c5268405a9bbc9d7d7ed5a658510a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
